/**
 * firebase-config.js
 * Firebase initialization + Remote Config setup for why57.com A/B testing.
 *
 * HOW IT WORKS:
 *   1. Initializes Firebase app with the project config below.
 *   2. Sets up Remote Config with default values that match current live copy.
 *   3. Fetches the latest variant assignments from Firebase (12hr cache in prod).
 *   4. Exposes `window.why57RC` — a key/value map of active parameter values.
 *   5. Dispatches a custom event `why57:rc-ready` so experiments.js can apply variants.
 *
 * UPDATING DEFAULTS:
 *   If you change live copy on the site, mirror that change in DEFAULT_CONFIG below
 *   so new visitors get the correct baseline while Remote Config loads.
 *
 * FIREBASE CONSOLE:
 *   https://console.firebase.google.com/project/why57-ab/remoteconfig
 *
 * CLI COMMANDS (Remote Config management):
 *   firebase remoteconfig:get -o experiments/rc-snapshot.json
 *   firebase remoteconfig:set experiments/rc-active.json
 */

import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import {
  getRemoteConfig,
  fetchAndActivate,
  getString,
  getBoolean,
} from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-remote-config.js';
import { getAnalytics, logEvent } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-analytics.js';

// ─── Project config ────────────────────────────────────────────────────────
// Values are injected at runtime by site-config.js (gitignored).
// In production, site-config.js is generated by GitHub Actions from secrets.
// Locally: copy site-config.example.js → site-config.js and fill in values.
const FIREBASE_CONFIG = window.WHY57_FIREBASE || {};

// ─── Default config (mirrors current live copy) ────────────────────────────
// These values are used before Remote Config loads and as baseline/control values.
// Each key maps to a Firebase Remote Config parameter.
const DEFAULT_CONFIG = {
  // Experiment 1 — Hero headline framing
  hero_headline:        "We build software that pays for itself.",
  hero_headline_sub:    "Automation. Client portals. Review engines. Operations platforms. Purpose-built for businesses in Sonoma County, the Bay Area, and beyond.",

  // Experiment 2 — Hero CTA copy
  hero_cta_primary:     "Book a Free Call",
  nav_cta:              "Book a Call",

  // Experiment 3 — Intake form position
  intake_above_fold:    false,           // boolean: show intake before hero content

  // Experiment 4 — Price signal near CTA
  show_price_signal:    false,           // boolean: show "Most projects: $5k–$25k" near CTA
  price_signal_text:    "Most projects: $5k–$25k · Fixed price, scoped upfront.",

  // Experiment 5 — Social proof placement
  social_proof_above_fold: false,        // boolean: show logo wall / stat row before hero text

  // Experiment 6 — 57Seconds as hero use case
  hero_badge_text:      "Custom Software Development",
  hero_lead_service:    "default",       // "default" | "57seconds" — controls hero emphasis
};

// ─── Init ──────────────────────────────────────────────────────────────────
let _rc = null;

async function initFirebase() {
  if (!FIREBASE_CONFIG.apiKey) {
    console.warn('[why57] Firebase config missing — copy site-config.example.js to site-config.js');
    window.why57RC = { ...DEFAULT_CONFIG };
    document.dispatchEvent(new CustomEvent('why57:rc-ready', { detail: window.why57RC }));
    return;
  }

  try {
    const app = initializeApp(FIREBASE_CONFIG);
    const analytics = getAnalytics(app);

    _rc = getRemoteConfig(app);

    // Apply defaults so page renders correctly before fetch completes
    _rc.defaultConfig = DEFAULT_CONFIG;

    // In production, Remote Config caches for 12 hours.
    // During development, set to 0 to always get fresh values.
    _rc.settings.minimumFetchIntervalMillis =
      ['localhost', '127.0.0.1'].includes(window.location.hostname) ? 0 : 43200000; // 12 hours

    // Fetch latest variant assignments from Firebase
    await fetchAndActivate(_rc);

    // Build the public config map consumed by experiments.js
    window.why57RC = {
      hero_headline:           getString(_rc, 'hero_headline'),
      hero_headline_sub:       getString(_rc, 'hero_headline_sub'),
      hero_cta_primary:        getString(_rc, 'hero_cta_primary'),
      nav_cta:                 getString(_rc, 'nav_cta'),
      intake_above_fold:       getBoolean(_rc, 'intake_above_fold'),
      show_price_signal:       getBoolean(_rc, 'show_price_signal'),
      price_signal_text:       getString(_rc, 'price_signal_text'),
      social_proof_above_fold: getBoolean(_rc, 'social_proof_above_fold'),
      hero_badge_text:         getString(_rc, 'hero_badge_text'),
      hero_lead_service:       getString(_rc, 'hero_lead_service'),
    };

    // Log successful RC fetch so we can track initialization rate in GA4
    logEvent(analytics, 'rc_fetch_success', { variant_count: Object.keys(window.why57RC).length });

  } catch (err) {
    // On failure, fall back to defaults — site still works normally
    console.warn('[why57] Remote Config fetch failed, using defaults:', err.message);
    window.why57RC = { ...DEFAULT_CONFIG };
  }

  // Signal that RC values are ready — experiments.js listens for this
  document.dispatchEvent(new CustomEvent('why57:rc-ready', { detail: window.why57RC }));
}

initFirebase();
