/**
 * site-config.example.js
 * Copy this file to site-config.js and fill in your values.
 * site-config.js is gitignored — never commit the real values.
 *
 * In production, site-config.js is generated by GitHub Actions
 * from repository secrets (see .github/workflows/deploy.yml).
 *
 * GA4 PROPERTY REFERENCE (why57.com):
 *   Property ID (numeric): 531150669
 *   Measurement ID:        G-358H0FHG50   ← use this for measurementId below
 *
 * NOTE: A second GA4 property (292639830 / G-0800YRKXPK) was created
 * accidentally and receives no traffic. Use ONLY 531150669 / G-358H0FHG50.
 */
window.WHY57_FIREBASE = {
  apiKey:            "YOUR_API_KEY",
  authDomain:        "YOUR_PROJECT.firebaseapp.com",
  projectId:         "YOUR_PROJECT",
  storageBucket:     "YOUR_PROJECT.firebasestorage.app",
  messagingSenderId: "YOUR_SENDER_ID",
  appId:             "YOUR_APP_ID",
  measurementId:     "G-358H0FHG50",   // GA4 Measurement ID for why57.com
};
