/**
 * site-config.example.js
 * Copy this file to site-config.js and fill in your values.
 * site-config.js is gitignored — never commit the real values.
 *
 * In production, site-config.js is generated by GitHub Actions
 * from repository secrets (see .github/workflows/deploy.yml).
 */
window.WHY57_FIREBASE = {
  apiKey:            "YOUR_API_KEY",
  authDomain:        "YOUR_PROJECT.firebaseapp.com",
  projectId:         "YOUR_PROJECT",
  storageBucket:     "YOUR_PROJECT.firebasestorage.app",
  messagingSenderId: "YOUR_SENDER_ID",
  appId:             "YOUR_APP_ID",
  measurementId:     "YOUR_MEASUREMENT_ID",
};
